# To enable profiling uncomment the following line
# zmodload zsh/zprof

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Set the directory we want to store zinit and plugins
ZINIT_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}/zinit/zinit.git"

# Download Zinit, if it's not there yet
if [ ! -d "$ZINIT_HOME" ]; then
   mkdir -p "$(dirname $ZINIT_HOME)"
   git clone https://github.com/zdharma-continuum/zinit.git "$ZINIT_HOME"
fi

# Source/Load zinit
source "${ZINIT_HOME}/zinit.zsh"

# Add in Powerlevel10k
zinit ice depth=1; zinit light romkatv/powerlevel10k

# Add in zsh plugins
zinit light zsh-users/zsh-syntax-highlighting
zinit light zsh-users/zsh-completions
zinit light zsh-users/zsh-autosuggestions
zinit light Aloxaf/fzf-tab
zinit light MichaelAquilina/zsh-you-should-use

# Add in snippets
zinit snippet OMZL::git.zsh
zinit snippet OMZP::git
zinit snippet OMZP::git-prompt
zinit snippet OMZP::command-not-found

# Completion for Brew based programs
if type brew &>/dev/null; then
    #FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
    FPATH="/opt/homebrew/share/zsh/site-functions:${FPATH}"
fi

# Load completions
autoload -Uz compinit && compinit

zinit cdreplay -q

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# Keybindings
bindkey '\' autosuggest-accept

# History
HISTSIZE=100000
HISTFILE=~/.zsh_history
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt appendhistory
setopt sharehistory
setopt hist_ignore_space
setopt hist_ignore_all_dups
setopt hist_save_no_dups
setopt hist_ignore_dups
setopt hist_find_no_dups

# Completion styling
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' menu no
zstyle ':fzf-tab:complete:cd:*' fzf-preview 'ls --color $realpath'

# Personal stuff
[[ ! -f ${HOME}/.zsh/functions.sh ]] || source ${HOME}/.zsh/functions.sh
[[ ! -f ${HOME}/.zsh/aliases.sh ]] || source ${HOME}/.zsh/aliases.sh
[[ ! -f ${HOME}/.zsh/env.sh ]] || source ${HOME}/.zsh/env.sh
[[ ! -f ${HOME}/.zsh/paths.sh ]] || source ${HOME}/.zsh/paths.sh

# Environment stuff not to be put into Git
[[ ! -f ${HOME}/.zsh_private_profile ]] || source ${HOME}/.zsh_private_profile

# Shell integrations
eval "$(fzf --zsh)"

# Enable VI mode
set -o vi
