SHELL := /bin/bash

main:
	./ansible-wrapper.sh

init:
	bash scripts/bootstrap.sh

git:
	./ansible-wrapper.sh git

shell:
	./ansible-wrapper.sh shell

paths:
	./ansible-wrapper.sh paths

misc:
	./ansible-wrapper.sh misc

macos:
	./ansible-wrapper.sh macos-settings

software:
	./ansible-wrapper.sh software

python:
	./ansible-wrapper.sh python
