---
- name: Enable Homebrew bundle tap
  homebrew_tap:
    name: homebrew/bundle
  tags:
    - software
    - brew

- name: Install mas
  homebrew:
    name: mas
    state: present
    update_homebrew: yes
  tags:
    - software
    - brew

- name: Check if Brewfile contains updates
  shell: 'brew bundle check --file="files/Brewfile"'
  register: bundle_check_result
  ignore_errors: true
  tags:
    - software
    - brew

- name: Install apps using Brewfile
  shell: 'brew bundle install --file="files/Brewfile" >> /tmp/mac-ansible.log'
  when: bundle_check_result.rc != 0
  tags:
    - software
    - brew

- name: Configure services
  command: "brew services start {{ item }}"
  loop: "{{ homebrew_services }}"
  tags:
    - software
    - brew

- name: Install NeoVIM & dependencies if not allready installed
  homebrew:
    name: "{{ item }}"
    state: present
    update_homebrew: no
  with_items:
    - neovim
    - lazygit
    - ripgrep
    - fzf
  tags:
    - software
    - neovim

- name: Checkout the custom NeoVIM config to {{ ansible_env.HOME }}/.config/nvim
  git:
    repo: "{{ neovim_custom_config_repo }}"
    dest: "{{ ansible_env.HOME }}/.config/nvim"
    update: "no"
  tags:
    - software
    - neovim
