---
- name: Check if {{ cloudfiles_path }}/ssh_config exists
  stat:
    path: "{{ cloudfiles_path }}/ssh_config"
  register: ssh_config_dir
  tags:
    - ssh

- name: Check for ~/.ssh directory
  stat:
    path: "{{ ansible_env.HOME }}/.ssh"
  register: ssh_home_dir
  tags:
    - ssh

- name: Setup SSH configuration
  block:
    - name: Create ~/.ssh dir
      file:
        path: "{{ ansible_env.HOME }}/.ssh"
        state: directory
        mode: "0755"

    - name: generate SSH key
      user:
        name: "{{ ansible_env.USER }}"
        generate_ssh_key: yes
        ssh_key_type: ed25519
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_ed25519
        ssh_key_comment: "{{ ansible_env.USER }}@{{ my_hostname }}"
        force: no

    - name: Set public key permissions
      file:
        path: "{{ ansible_env.HOME }}/.ssh/id_ed25519.pub"
        mode: "0644"

    - name: Set private key permissions
      file:
        path: "{{ ansible_env.HOME }}/.ssh/id_ed25519"
        mode: "0600"

    - name: Create authorized keys file
      file:
        path: "{{ ansible_env.HOME }}/.ssh/authorized_keys"
        state: touch
        mode: "0600"

  when:
    - not ssh_config_dir.stat.exists
  tags:
    - ssh

- name: Link ~/.ssh directory to {{ cloudfiles_path }}/ssh_config
  file:
    src: "{{ cloudfiles_path }}/ssh_config"
    dest: "{{ ansible_env.HOME }}/.ssh"
    state: link
  when:
    - ssh_config_dir.stat.exists
    - not ssh_home_dir.stat.exists
  tags:
    - ssh
